name: Build image

on:
  # workflow_call:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Docker build'
      run: |
        docker build -t ghcr.io/uuboyscy/prefect-demo:latest .
        docker push ghcr.io/uuboyscy/prefect-demo:latest
